package com.sequenceiq.cloudbreak.shell.model;

public enum AwsInstanceType {

    M1Medium,
    M1Large,
    M1Xlarge,
    M3Medium,
    M3Large,
    M3Xlarge,
    M32xlarge,
    M2Xlarge,
    M22xlarge,
    M24xlarge,
    Cr18xlarge,
    I2Xlarge,
    I22xlarge,
    I24xlarge,
    I28xlarge,
    Hi14xlarge,
    Hs18xlarge,
    C1Medium,
    C1Xlarge,
    C3Large,
    C3Xlarge,
    C32xlarge,
    C34xlarge,
    C38xlarge,
    Cc14xlarge,
    Cc28xlarge,
    G22xlarge,
    Cg14xlarge,
    R3Large,
    R3Xlarge,
    R32xlarge,
    R34xlarge,
    R38xlarge
}
